### ISSUE TITLE
Always output the same units

### ISSUE THREAD

**Issue by tfausak** [vincenthz/hs-gauge#1]
I haven't actually run Gauge yet, but I assume the output looks similar to Criterion. One thing that always trips me up is comparing timings with different units. How do `123 ns`, `234 μs`, and `345 ms` compare? It would be nice if Gauge always output the same unit (probably `ns`).

**Comment by NorfairKing** [comment]
Also on that topic: Please right-align these numbers, with an aligned decimal point:

Not this:

```
   123.4 ns
    4.53 ns
```

but this:

```
  123.4  ns
    4.53 ns
```

**Comment by harendra-kumar** [comment]
Even better this:

```
123.40 ns
  4.53 ns
```

**Comment by NorfairKing** [comment]
@harendra-kumar 
These two things don't mean the same thing:

```
  123.4  ns
    4.53 ns
```

```
123.40 ns
  4.53 ns
```

**Comment by harendra-kumar** [comment]
Do you mean precision? Does anyone care about precision here? I think readability (and the ability to quickly compare) is more important.

**Comment by vincenthz** [comment]
So this is the method I'm planning to use (with the separating char an option, and the base of this being the nanoseconds):

```
-- 0           -> "             0"
-- 1000        -> "         1_000"
-- 1234567     -> "     1_234_567"
-- 10200300400 -> "10_200_300_400"
```

**Comment by vincenthz** [comment]
Related to the precision, since the resolution of measurement is at the nanoseconds for the best case, it's unnecessary to print more except maybe for the stddev or mean which could have 1 digit of the picoseconds printed.

**Comment by knupfer** [comment]
Why don't we use scientific notation with lets say 4 significant digits?

```
-- 0 ns          -> 0.000 e-9 s
-- 1000 ns       -> 1.000 e-6 s
-- 1234567 ns    -> 1.235 e-3 s
-- 1020030040 ns -> 1.020 e-0 s
```

This doesn't show excessive information and can scale in both directions without problems.

**Comment by tfausak** [comment]
I prefer always using nanoseconds to using scientific notation. 

```
easy: 1234    vs 123400000
hard: 1.234e3 vs 1.234e8
```

I also don't particularly care about significant figures. If there are digits after the decimal point, I'd prefer everything to have the same number. Precision could be represented as `+- x`.

```
123.456 +- 0.001
123.000 +- 1
```

**Comment by knupfer** [comment]
Well, in nanoseconds you presumably won't need a decimal point. I'd argue that your hard example is easier to read. It's the whole reason this type of notation was introduced in the scientific community. If you write everything in nanoseconds, a function which takes a second will be quite hard on the eyes to decide whether it's 0.1s or 1s.

**Comment by NorfairKing** [comment]
@knupfer The scientific notation makes it very hard which measurement is bigger at a glance.

Related:
https://xkcd.com/558/

**Comment by knupfer** [comment]
Hm, obviously a notion of `very hard to read` is subjective. I'd argue that it would be more productive to discuss arguments and not postulate preference as objective truth.

**Comment by vincenthz** [comment]
It depends whether you're comparing values against other values (relative), or that you want to know the value itself (absolute). For example when comparing `1.434 us` and `330.2 ns`, it's useful to use the same unit and having them represented from instantly unreadable:

```
benchmark1   1.434 us
benchmark2   330.2 ns
```

to instantly readable:

```
benchmark1    1434 ns
benchmark2     330 ns
```

This is very different for quick human processing. I don't think scientific notation make it better in this aspect. However when wanting an absolute value, clearly the unit (or scientific) notation are better for fast processing.

**Comment by AndreasPK** [comment]
> Does anyone care about precision here?

I do. Especially if it can be had with little cost.
