### ISSUE TITLE
Automatically find the gauge executable for --measure-with when possible

### ISSUE THREAD

**Issue by harendra-kumar** [vincenthz/hs-gauge#12]
PR #3 introduced `--measure-with` option for isolated measurement. This option requires the user to specify the path of the gauge executable itself so that it can be invoked again for running benchmarks in isolation. This is inconvenient for the user, we can find this automatically in most cases if not all.

On Unices the exact path of the executable can be figured out as it was invoked and we can use that. On Windows that is not possible, only the name of the executable can be determined. However if the gauge executable is in PATH we can try to find an executable of that name in the PATH. If we still cannot find it then we can ask the user to use `--measure-with` to specify the path.

For automatic determination we can use `--isolate` command line switch and in the same vein the `--measure-with` option can be renamed to `--isolate-with` to keep the two options intuitively related.

**Comment by sjakobi** [comment]
Actually there's a package on Hackage with an `getExecutablePath` function that is supposed to work on many OSs:

http://hackage.haskell.org/package/executable-path-0.0.3.1/docs/System-Environment-Executable.html#v:getExecutablePath
