### ISSUE TITLE
Make calculation takes integral numbers

### ISSUE THREAD

**Issue by vincenthz** [vincenthz/hs-gauge#16]
it would be more accurate to have calculation done on floating points at the 10 or 100 picoseconds level instead of relying on `Double` doing the right thing related to rounding. Some calculation might still require `Double` convertion, but some like (min, max... don't)

**Comment by istathar** [comment]
I wrote a tiny package that uses Int64 for timestamps in nanoseconds (wraps **hourglass** to get nanosecond resolution timestamps from operating system, actually). You obviously don't need a dependency on my thing but fwiw Int64 works out nicely for this sort of application.
https://hackage.haskell.org/package/chronologique fwiw

**Comment by ocramz** [comment]
Hi @afcowie , chronologique looks good, does it have an issue tracker/public repo?

**Comment by istathar** [comment]
@ocramz oh, damn, sorry for the oversight. Thanks for pointing it out. Code is at <https://github.com/afcowie/chronologique/>. I just did a point release with the links added to the _.cabal_ file.
