### ISSUE TITLE
Design of the command line interface

### ISSUE THREAD

**Issue by harendra-kumar** [vincenthz/hs-gauge#29]
It may be a good idea to use a command based CLI interface using a command for logical sets of tasks. For example, I can imagine the following commands (with their own options not shown here):

```
$ gauge list     # List all available benchmarks
$ gauge evlist   # List all available event counters
$ gauge stats    # Run selected benchmarks and measure selected counter stats
$ gauge report   # Read the raw perf data file and generate a report (text, html, ...)
$ gauge diff     # Show a nice diff between two raw perf data files
```

Where possible we can also take cues from the Linux `perf` tool.

**Comment by vincenthz** [comment]
I think it's a good idea, but it will have to be a different `defaultMain` (e.g. `defaultMain2`). I think keeping the current CLI is really important to make sure people can move from `crirterion` to `gauge` without changing everything.

Also whatever is listed here is clearly where I want to go with this (mainly stats, report, diff), and having a sub command make the CLI much nicer to use imho.

**Comment by harendra-kumar** [comment]
Looks like our ideas about the tool match a lot. In general I would like it to be microbenchmarking tool filling the need where `perf` cannot be used e.g. benchmarking code snippets rather than processes. `perf` is awesome and very versatile, provides tons of useful information but at a higher granularity and it is Linux only. Since it is a mature tool, we can pick ideas from perf and apply them in our context.

Yes, using a different `defaultMain` is good idea, it does not cost us much. We can maintain the existing defaultMain separately. I believe it provides familiarity and compatibility of CLI to existing users. Not sure how important it is in general but could be important in initial adoption and transition.

**Comment by harendra-kumar** [comment]
> $ gauge list     # List all available benchmarks
$ gauge evlist   # List all available event counters

Or we can rather use a single list command and have `bench` and `event` as subcommands of the list command. Later if we have other things to list that can also be added as a subcommand rather than polluting the main command namespace.
