### ISSUE TITLE
utime and stime should not  be printed when they are not available (on windows)

### ISSUE THREAD

**Issue by harendra-kumar** [vincenthz/hs-gauge#31]
@vincenthz Commit 3f03bc94306b4326f7f1a88d8f67d9b35921af3b had fixed this problem but this seems to have been nullified by the merge of new `getrusage` FFI changes.

**Comment by vincenthz** [comment]
This is because of the use of the wrong bound (minBound -> maxBound) to support a valid/invalid reading

**Comment by vincenthz** [comment]
I'm hoping to fix this at the type system instead of the awful fromInt/fromWord/fromDouble stuff...
