### ISSUE TITLE
Formatting numbers

### ISSUE THREAD

**Issue by harendra-kumar** [vincenthz/hs-gauge#33]
Big numbers are difficult to read without separators. What is the best way to format them? I found https://hackage.haskell.org/package/format-numbers on hackage for this purpose, which is a tiny package. Should we put a dependency for this or just copy over the code, or are there better options in base or something we already depend on? Or write our own?

**Comment by vincenthz** [comment]
I think writing our own (which is not very hard) is the best option since I can imagine being in control of the displaying very precisely is key to a nice UX and that related to #1.

**Comment by vincenthz** [comment]
I've added some formatting tool in the formatting branch for printing numbers and markdown tables
