### ISSUE TITLE
Print messages on stdout instead of stderr

### ISSUE THREAD

**Issue by harendra-kumar** [vincenthz/hs-gauge#36]
It seems the benchmark results are being printed on stderr. Shouldn't they be printed on stdout instead?

**Comment by vincenthz** [comment]
seems that everything is printed to stdout, apart from call to `printError` (which is not used for printing benchmark results)

**Comment by harendra-kumar** [comment]
This is what I get from an old client:

```
$ stack bench > /dev/null
streaming-benchmarks-0.1: benchmarks
Running 1 benchmarks...
Benchmark benchmarks: RUNNING...
benchmarked elimination/null/conduit
time                 42.58 ms   (41.88 ms .. 43.22 ms)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 43.64 ms   (43.18 ms .. 44.75 ms)
std dev              1.364 ms   (569.1 μs .. 2.376 ms)

benchmarked elimination/null/pipes
time                 22.22 ms   (21.91 ms .. 22.61 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 22.44 ms   (22.25 ms .. 22.77 ms)
std dev              611.9 μs   (405.0 μs .. 958.4 μs)
```

Let me check after syncing.

**Comment by harendra-kumar** [comment]
Its the same on latest commit as well, it does not come on stdout.

**Comment by harendra-kumar** [comment]
Or is it a stack issue instead?

**Comment by vincenthz** [comment]
yes, it's linked to how `stack bench` works (everything is redirected to a file and then printed back by stack).

**Comment by vincenthz** [comment]
I think that wasn't an issue in gauge, closing for now
