### ISSUE TITLE
Build failures with GHC-7.8

### ISSUE THREAD

**Issue by sjakobi** [vincenthz/hs-gauge#41]
I've sadly lost my build logs but when I tried to build with `lts-2.22` I ran into a bad import from `math-functions` and missing imports of `pure`.

Currently the cabal file claims that you're testing with GHC-7.8 so you should do probably that. :)

Nice package BTW. Looks very useful for benchmarking dependencies of `criterion`! :)

**Comment by vincenthz** [comment]
OT but I remove dependency on containers too in #43, since it's really not needed. that should make it even smoother
