### ISSUE TITLE
Add 'Semigroup' instance to 'Outliers'

### ISSUE THREAD

**Issue by vrom911** [vincenthz/hs-gauge#57]
Currently there's only `instance Monoid Outliers`. Without `Semigroup` instance it's impossible to build `gauge` using `ghc-8.4.1`:

https://github.com/vincenthz/hs-gauge/blob/69d302bf93ac8e2fb1e60da5241d15a4f2713c80/Gauge/Analysis.hs#L109

**Comment by vincenthz** [comment]
Thanks for reporting @vrom911, sadly I can't integrate any testing of ghc 8.4 until there's primitive package being release. https://github.com/haskell/primitive/issues/72

I've removed the instance of Monoid in the meantime, as they are fairly useless anyway

**Comment by vrom911** [comment]
@vincenthz , thank you very much! Could you please also release the newest version with this changes on hackage?

**Comment by vincenthz** [comment]
yes, I will really soon (prod me again if I forget). I just want to fix another problem and finish a little improvement
