### ISSUE TITLE
Hackage Release

### ISSUE THREAD

**Issue by andrewthad** [vincenthz/hs-gauge#65]
Can this be released to hackage? I want to switch to this for benchmarking suites in most of my libraries (since I never need criterion's plots), but not having a hackage release is a showstopper.

**Comment by sjakobi** [comment]
gauge has been [on Hackage](https://hackage.haskell.org/package/gauge) for a while.

**Comment by andrewthad** [comment]
Looks like I've been misspelling gauge my whole life. Sorry for the noise. Also, as a PSA to future chronic misspellers: the a comes before the u.
