### ISSUE TITLE
Comparison chart

### ISSUE THREAD

**Issue by chrisdone** [vincenthz/hs-gauge#67]
I'd like a simple terminal comparison output a la the graphical output of Criterion. How about if I submit a PR with something like the below if you pass `--bars`?

```
bench1    ██████░░░░░░   41.65 ns
bench2    ████████████   163.9 ns
bench3    ██░░░░░░░░░░   21.25 ns
````

**Comment by vincenthz** [comment]
This would be very nice; not sure how to structure this, since the benchmark are at the moment indepedent from each other.

presumably you'ld need to hold on the final values of each benchmarks and display at the end of a group the bars ?
