### ISSUE TITLE
semantics of whnf (documentation issue?)

### ISSUE THREAD

**Issue by jwaldmann** [vincenthz/hs-gauge#95]
Gauge.Benchmark.whnf doc says "Apply an argument to a function, and evaluate the result to weak head normal form (WHNF)." What it does *not* say is whether the time needed for evaluating the argument is included in the measurement, or not.

I guess it is not, and I take the following experiment as confirmation:
```
Prelude Gauge.Main> benchmark $ whnf id (sum . enumFromTo 0 $ 1000)
benchmarking function ... took 16.17 s, total 60947101 iterations
function                                 time                 23.96 ns  

Prelude Gauge.Main> benchmark $ whnf (sum . enumFromTo 0) 1000
benchmarking function ... took 6.913 s, total 20152 iterations
function                                 time                 47.58 μs  
```
But what exactly *is* the semantics: the argument (value) simply is shared? So the cost of its computation is accounted for by the first function call? Or is the argument forced (to WHNF?) before that? (That would be better?)

**Comment by harendra-kumar** [comment]
This is a good question and anyone working with the package for the first time may have the same question. Perhaps we need to document the exact semantics in a better way.

Technically, the argument evaluation is in fact included in the measurement. By default we perform many iterations and the argument evaluation happens only once in the first iteration, in the later iterations the previously evaluated result is used. By default we discard the results of the first iteration so the argument evaluation cost gets excluded from the results. You can try using the following command to check what happens in the first iteration:

```
$ cat bench.hs
import Gauge

main = defaultMain
    [bench "x" $ whnf id (sum . enumFromTo 0 $ 1000)]

$ bench --quick --include-first-iter --min-duration 0 
```

This command makes it perform exactly one iteration. If you remove the `--include-first-iter` option it will report a different result.

Would you be willing to improve the documentation with more precise/accurate details? I can help in reviewing it.

**Comment by jwaldmann** [comment]
Yes I can try to propose a sentence to add to the documentation. 

Just to be clear: from your explanation I conclude that `evaluate $ rnf [s, s_even, s_odd]` is unnecessary in https://github.com/haskell/containers/blob/master/containers-tests/benchmarks/IntSet.hs#L15 
(because the first call will evaluate it anyway, and its time will be discarded)?

**Comment by harendra-kumar** [comment]
Yes, that's correct. It should be unnecessary.

**Comment by treeowl** [comment]
@jwaldmann a lot of the "set up the environment" business in the `containers` benchmarks is and has always been somewhat broken. But thanks to the discarding, it seems to work okay anyway. We should clean it up at some point.

**Comment by harendra-kumar** [comment]
Also, be aware that sometimes sharing can affect the results of benchmarks that run later when we have a list of multiple benchmarks. I have experienced this problem several times and I ended up implementing the `--measure-with` flag in gauge to avoid this. It runs each benchmark in an isolated process by invoking the benchmark exe from itself. To be completely sure about the results I always use that option to at least verify that the results don't change.

**Comment by harendra-kumar** [comment]
One big surprise that I recently discovered is that at times the `NFData` instance of what you are measuring may not be optimal (e.g. due to a missing INLINE). You might think that your code performs poorly but it is the `NFData` instance that performs poorly. In one of my benchmark suites I have switched to manual evaluation instead of relying on `NFData`.
