### ISSUE TITLE
documentation of command line options

### ISSUE THREAD

**Issue by jwaldmann** [vincenthz/hs-gauge#97]
It took me some time to find out that I can select benchmarks on the command line (`my-benchmark-exe -m pattern foobar`) 

I suggest to show some typical ways of calling an executable that uses `defaultMain`, right at https://hackage.haskell.org/package/gauge-0.2.4/docs/Gauge-Main.html#v:defaultMain , and maybe even at the top page https://hackage.haskell.org/package/gauge-0.2.4 , and some text like 

> An executable that uses `defaultMain` 
> is called from the command line as `executable <options> <arguments>`
> where options are described at https://hackage.haskell.org/package/gauge/docs/src/Gauge.Main.Options.html#opts , and each argument is a benchmark name (or pattern)

Current documentation/landing page adresses people that want to switch from `criterion` (and wastes a lot of space by listing libraries that are avoided) - but my use case is that I want to evaluate `gauge` (or recommend it to my students) without previous knowledge of other frameworks. 

(NB: I find criterion's `defaultMain` equally underdocumented.)

**Comment by harendra-kumar** [comment]
I agree easy discoverability of features is important for people to use them. I agree with your suggestions above. We can also suggest the user to run the executable created by `defaultMain` with `--help` CLI option to find out the various CLI options supported.

**Comment by jwaldmann** [comment]
The `--help` proposal is already there. But it requires me to download, install, build, and run - or to hunt for the source code. Neither of these (output of `--help`, source code) does say anything about arguments.
